version: '3.8'

services:
  django:
    build:
      context: ./
      dockerfile: blitz_project/Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./blitz_project:/app
    environment:
      DJANGO_ALLOWED_HOSTS: localhost
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  discord_bot:
    build:
      context: ./
      dockerfile: discord_project_bot/Dockerfile
    container_name: discord_bot
    volumes:
      - ./discord_project_bot:/app
    env_file:
      - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_BOT_TOKEN}
    restart: always
    depends_on:
      - django
