# Generated by Django 5.1.4 on 2024-12-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0002_moviespage_musicpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('primaryImage', models.URLField()),
                ('description', models.TextField()),
                ('startYear', models.PositiveIntegerField()),
                ('endYear', models.PositiveIntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.PositiveIntegerField()),
                ('contentRating', models.CharField(blank=True, max_length=10, null=True)),
                ('averageRating', models.FloatField()),
                ('numVotes', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviespage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='moviespage',
            name='title',
        ),
    ]
