# Generated by Django 5.1.4 on 2024-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0003_movie_remove_moviespage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('primaryImage', models.URLField()),
                ('description', models.TextField()),
                ('startYear', models.PositiveIntegerField()),
                ('endYear', models.PositiveIntegerField(blank=True, null=True)),
                ('totalEpisodes', models.PositiveIntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.PositiveIntegerField()),
                ('contentRating', models.CharField(blank=True, max_length=10, null=True)),
                ('averageRating', models.FloatField()),
                ('numVotes', models.PositiveIntegerField()),
                ('type', models.CharField(default='tvSeries', max_length=50)),
            ],
        ),
    ]
