# Generated by Django 5.1.4 on 2024-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0004_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='runtimeMinutes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
