# Generated by Django 5.1.4 on 2024-12-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0005_alter_series_runtimeminutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviesPage',
        ),
        migrations.DeleteModel(
            name='MusicPage',
        ),
    ]
