# Generated by Django 5.1.4 on 2024-12-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0006_delete_moviespage_delete_musicpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
