# Generated by Django 5.1.4 on 2024-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0007_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('songs', models.TextField()),
            ],
        ),
    ]
