# Generated by Django 5.1.4 on 2024-12-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0008_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
