# Generated by Django 5.1.4 on 2024-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0009_artists_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
