# Generated by Django 5.1.4 on 2024-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blitz_games_app', '0011_alter_artists_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image',
            field=models.URLField(default='https://images.genius.com/70b44d7b5a4be028e87b865dd425a4cc.1000x1000x1.jpg?fbclid=IwY2xjawHZ_pVleHRuA2FlbQIxMAABHVKYXUBpNOpt88G5n1ud6yrjE1poAYn_qPfqh_v6y19_bZNvyshX5KLVMQ_aem_KjY0eUbttaqZK8vJ_v1NGg'),
        ),
    ]
